# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='column_id',
            field=models.CharField(default='dummy', max_length=200, verbose_name='Column ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='User ID'),
            preserve_default=False,
        ),
    ]
