# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_auto_20161203_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='user_id',
            field=models.CharField(max_length=200, verbose_name='User ID'),
        ),
    ]
